### ISSUE TITLE
Use other instant messaging networks through Matrix

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#165]
Would it be possible within the current protocol specification to use other networks through Matrix? For example there could be a Matrix server that is also a client to some other network such as Telegram. Users would be able to use Telegram networks using this server. People could search for Telegram groups and users and results would be returned to your Matrix client. You would be also able to create Telegram rooms using this server.

**Comment by homebeach** [comment]
This would be useful for example if some network such as Telegram is blocker in your country and you cannot make straight connection.

**Comment by mvgorcum** [comment]
That is basically what bridging is all about. Different types of bridges can have more or less of these features, depending on how they are implemented.

There is a pretty good telegram bridge called [mautrix-telegram](https://github.com/tulir/mautrix-telegram).

**Comment by homebeach** [comment]
Well you can bridge channels but what if the Matrix server could be used as a bouncer to other network? For example there would be a Matrix server that is also a bouncer to IRCnet.

**Comment by mvgorcum** [comment]
Yes, like I said, that is what bridges are for. The IRC bridges for instance allow you to join any room on a certain server. 

Depending on how the bridge is written you can do more or less of the features mentioned. See [here](https://matrix.org/docs/guides/types-of-bridging.html).

**Comment by homebeach** [comment]
With default bridge you can join room to IRC channel. But what if there would be some kind of prompt window that lets you to join IRC channel just with your user? When bridging with another channel you could use it to go to ask from channel operators if bridging is ok just using your Matrix client.

**Comment by mvgorcum** [comment]
There *is* a method for you to join any IRC channel on a bridged server as a user. See [here](https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks).

**Comment by homebeach** [comment]
Ok cool. But does it work from IRC to Matrix? What about other networks such as XMPP? All the open protocol networks could be bridged like this.

**Comment by mvgorcum** [comment]
The whole point of matrix is that this is indeed more or less the plan. Everything has to get some kind of bridge or connection to matrix such that you can talk to anyone from basically any silo.

Of course that takes time and energy. Either way: this issue is basically: "please bridge matrix to everything" which is on the one hand basically the mission statement of matrix, and on the other hand not really a concrete issue. I don't really think this is the right place to discuss this.

If you want to see what's already been built: look at [try matrix now](https://matrix.org/docs/projects/try-matrix-now.html). That's as close to an exhaustive list of available matrix projects you'll find. 

Also: see [here](https://mobile.twitter.com/matrixdotorg/status/841424770025545730).

I'd say this issue should be closed.
